name: Publish
on:
  release:
    types:
      - released
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repository
        uses: "actions/checkout@v4.1.7"
      - name: Set up JDK
        uses: "actions/setup-java@v4.2.2"
        with:
          distribution: temurin
          java-version: 21
          cache: gradle
      - name: Cache Gradle files
        uses: "actions/cache@v4.0.2"
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: ${{ runner.os }}-gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build JARs
        uses: Wandalen/wretry.action@master
        with:
          command: "gradlew chiseledBuild"
          attempt_limit: 3
      - name: Upload built JARs
        uses: "actions/upload-artifact@v4.3.6"
        with:
          name: EventUtils
          path: |
            ./versions/**/build/libs/*.jar

  distribute:
    needs: build
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        # REMINDER: Update this when adding new game versions
        game_version: [
          "1.21.1"
          "1.21",
          "1.20.6",
          "1.20.5",
          "1.20.4",
          "1.20.3",
          "1.20.2",
          "1.20.1",
        ]
    steps:
      - name: Checkout repository
        uses: "actions/checkout@v4.1.7"
      - name: Download Built JARs
        uses: actions/download-artifact@v4
        with:
          name: EventUtils
          path: ./versions
      - name: Publish
        uses: "Kir-Antipov/mc-publish@v3.3.0"
        with:
          fail-mode: warn
          modrinth-id: ZcRRACSs
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          github-token: ${{ secrets.CLASSIC_GITHUB_TOKEN }}
          files: versions/${{ matrix.game_version }}/build/libs/*.jar
          version: ${{ matrix.game_version }}-${{ github.ref_name }}
          loaders: fabric
          dependencies: |
            fabric-api
            yacl
